### ISSUE TITLE
As of now I get the error of "ImportError: No module named related"

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [karanlyons/django-save-the-change#16]

**Comment by howardjones** [comment]
This seems to be resolved in the master branch. I was getting this error too with Django 1.9 and the pip-installed version 1.1 of save-the-change. Then I noticed that was from 2014 and the most recent changes on github are from 3 months ago.

**Comment by karanlyons** [comment]
Fixed in 2.0.
