### ISSUE TITLE
Next Release version

### ISSUE THREAD

**Issue by phpdude** [karanlyons/django-save-the-change#18]
Hi @karanlyons,

Can you please publish new release with fixed support of Django 1.9+ to pypi?

If this is stable i think a lot of people would like to be able to install curently supported version from pypi :)

Please do it if you have time for this.

Thanks you for your library.

**Comment by phpdude** [comment]
Ping, is anybody alive here? :)

**Comment by karanlyons** [comment]
Hi! I’m quite alive, but had unfortunately been quite busy for quite a while. The nature of this kind of open source is that you’re pretty much working alone and for free, which didn’t make things any easier.

I’ve got a new version of this package almost ready to go, so I’m going to mark this closed, and push out the new release to PyPI just as soon as I’m sure it’s tested thoroughly.
