### ISSUE TITLE
OldData cannot be transformed to a dict when it has a reverse m2o relationship

### ISSUE THREAD

**Issue by gcbirzan** [karanlyons/django-save-the-change#20]
This is because `m._meta.get_fields()` returns fields that aren't concrete, in particular the reverse relationship:

```
class SomeModel(models.Model):
    some_field = models.IntegerField()


class SomeOtherModel(models.Model):
    some_random_field = models.IntegerField()
    some_relationship = models.ForeignKey(SomeModel)
```

Then, `SomeModel()._meta.get_fields()` returns:

```
(<ManyToOneRel: appname.someothermodel>,
 <django.db.models.fields.AutoField: id>,
 <django.db.models.fields.IntegerField: some_field>)

```

When you then try to access `OldData['someothermodel']`, that obviously doesn't work and explodes with a key error, so you cannot easily transform OldData to a dict.

**Comment by karanlyons** [comment]
This should *probably* return a queryset? Not honestly sure, but I’ll put it on my list of things to fix in STC just as soon as I’ve got some spare time from my paid gig.
